In [ ]:
# DT, RF, SVM, LR, K-NN 
# heart.csv

In [4]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder

In [6]:
# CSV 파일 불러오기
df = pd.read_csv("C:/AI/heart.csv", index_col=0)
df

# 1. 데이터 전처리 (X: 특성, y: 타겟)
print("결측치 확인:\n", df.isnull().sum())
X = df.drop(columns=['target'])
y = df["target"]

# 2. 데이터 분할 (훈련 80%, 테스트 20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 4. 모델 학습
model_DT = DecisionTreeClassifier() 
model_RF = RandomForestClassifier()
model_SVM = SVC()
model_LR = LogisticRegression()

model_DT.fit(X_train, y_train)
model_RF.fit(X_train, y_train)
model_SVM.fit(X_train, y_train)
model_LR.fit(X_train, y_train)

# 5. 예측 및 정확도 평가
print("<<Result>>")
y_pred_DT = model_DT.predict(X_test)
accuracy_DT = accuracy_score(y_test, y_pred_DT)
print(f"1. Decision Tree Accuracy: {accuracy_DT:.4f}")
cm_DT = confusion_matrix(y_test, y_pred_DT)
print("\n1-2. Confusion Matrix Result:\n", cm_DT)

y_pred_RF = model_RF.predict(X_test)
accuracy_RF = accuracy_score(y_test, y_pred_RF)
print(f"2. Random Forest Accuracy: {accuracy_RF:.4f}")
cm_RF = confusion_matrix(y_test, y_pred_RF)
print("\n2-2. Confusion Matrix Result:\n", cm_RF)

y_pred_SVM = model_SVM.predict(X_test)
accuracy_SVM = accuracy_score(y_test, y_pred_SVM)
print(f"3. Support Vector Machine Accuracy: {accuracy_SVM:.4f}")
cm_SVM = confusion_matrix(y_test, y_pred_SVM)
print("\n3-2. Confusion Matrix Result:\n", cm_SVM)

y_pred_LR = model_LR.predict(X_test)
accuracy_LR = accuracy_score(y_test, y_pred_LR)
print(f"4. Logistic Regression Accuracy: {accuracy_LR:.4f}")
cm_LR = confusion_matrix(y_test, y_pred_LR)
print("\n6. K-NN 결과의 Confusion Matrix Result:\n", cm_LR)

# 5. K-NN 모델 학습 (K=3)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

knn_clf = KNeighborsClassifier(n_neighbors=3)
knn_clf.fit(X_train, y_train)
y_pred_class = knn_clf.predict(X_test)
accuracy = knn_clf.score(X_test, y_test)
print(f"5-1. K-NN Classification 정확도: {accuracy:.2f}")

k_values = range(1, 21)  # K값 범위 설정
scores = []

for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)  # K-NN 모델 생성
    knn.fit(X_train, y_train)  # 학습
    y_pred = knn.predict(X_test)  # 예측
    accuracy = accuracy_score(y_test, y_pred)  # 정확도 계산
    scores.append(accuracy)
    
# 최적의 K 값 찾기
best_k = k_values[np.argmax(scores)]
print(f"5-2. 최적의 K 값: {best_k}")

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("\n5-3. K-NN 결과의 Confusion Matrix Result:\n", cm)

결측치 확인:
 sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64
<<Result>>
1. Decision Tree Accuracy: 0.7869

1-2. Confusion Matrix Result:
 [[24  5]
 [ 8 24]]
2. Random Forest Accuracy: 0.8525

2-2. Confusion Matrix Result:
 [[25  4]
 [ 5 27]]
3. Support Vector Machine Accuracy: 0.7049

3-2. Confusion Matrix Result:
 [[15 14]
 [ 4 28]]
4. Logistic Regression Accuracy: 0.8689

6. K-NN 결과의 Confusion Matrix Result:
 [[25  4]
 [ 4 28]]
5-1. K-NN Classification 정확도: 0.87
5-2. 최적의 K 값: 13

6. K-NN 결과의 Confusion Matrix Result:
 [[25  4]
 [ 3 29]]


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
